apiVersion: v1
kind: Namespace
metadata:
  name: finance-aviad
---
apiVersion: v1
kind: Pod
metadata:
  name: temp-bus
  namespace: finance-aviad
spec:
  containers:
  - name: redis-container
    image: redis:alpine
    resources:
      limits:
        memory: "256Mi"
        cpu: "150m"

