apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-aviad
  labels:
    name: nginx-pod-aviad
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources: {}
    ports:
      - containerPort: 8443



